--INSERTING A NEW EMPLOYEE
INSERT INTO EMPLOYEE(LAST_NAME,FIRST_NAME,HIRE_DATE,BIRTHDATE,SALARY_AMOUNT,EMPLOYEE_NUMBER)
VALUES (  ARCIA', ARIA',861027,541110,76500.00,1291);

--INSERTING A WHOLE ROW
INSERT INTO EMPLOYEE
VALUES ( 1210,NULL,401,41201, MITH', AMES',890303.460421,41000);

--INSERT-SELECT
INSERT INTO EMP_COPY
SELECT * FROM EMP;

--UPDATE THE ROWS
UPDATE EMPLOYEE
SET DEPARTMENT_NUMBER = 403
,JOB_CODE = 432101
,MANAGER_EMPLOYEE_NUMBER=1005
WHERE EMPLOYEE_NUMBER = 1010;

--UPDATE USING CLAUSES
UPDATE EMPLOYEE
SET SALARY_AMOUNT = SALARY_AMOUNT * 1.10
WHERE DEPARTMENT_NUMBER IN
(SELECT DEPARTMENT_NUMBER
FROM DEPARTMENT
WHERE DEPARTMENT_NAME LIKE '%SUPPORT%');

--DELETING FROM THE LIST
DELETE FROM EMPLOYEE
WHERE DEPARTMENT_NUMBER=301;

--DELETING ALL
DELETE FROM EMPLOYEE;

