--USAGE AND PRACTICE WITH MACRO
CREATE MACRO DEPT_LIST(DEPT INTEGER)
AS
(SELECT LAST_NAME
FROM EMPLOYEE
WHERE DEPARTMENT_NUMBER =:DERPT);

EXEC DEPT_LIST(301);

CREATE MACRO NEW_DEPT
(DEPT INTEGER
,BUDGETDEC(10,2) DEFAULT 0
,NAME CHAR(30)
,MGR INTEGER)
AS 
(INSERT INTO DEPARTMENT
(DEPARTMENT_NUMBER
,DEPARTMENT_NAME
,BUDGET_AMOUNT
,MANAGER_EMPLOYEE_NUMBER)
VALUES(:DEPT
,:NAME
,:BUDGET
,:MGR);

SELECT DEPARTMENT_NUMBER(TITLE 'NUMBER')
,DEPARTMENT_NAME (TITLE 'NAME')
,BUDGET_AMOUNT (TITLE 'BUDGET')
,MANAGER_EMPLOYEE_NUMBER(TITLE 'MANAGER')
FROM DEPARTMENT
WHERE DEPARTMENT_NUMBER = :DEPT;)

CREATE MACRO NEW_EMPLOYEE
(NUMBER INTEGER
,MGR INTEGER
,DEPT INTEGER
,JOB INTEGER
,LASTNAME CHAR(20)
,FIRSTNAME VARCHAR(30)
,HIRED DATE
,BIRTH DATE
,SALARY DECIMAL (10,2))
AS
(ROLLBACK WORK 'INVALID DEPARTMENT'
WHERE (:HIRED-:BIRTH)/365<21;
ROLLBACK WORK 'INVALID DEPARTMENT'
WHERE :DEPT NOT IN
(SELECT DEPARTMENT_NUMBER FROM DEPARTMENT
WHERE DEPARTMENT_NUMBER =: DEPT)))

