DATABASE	CUSTOMER_SERVICE;
GRANT	SELECT 
	ON	CUSTOMER_SERVICE TO DBC;

--CREATES A NEW TABLE
CREATE TABLE TABLE1(FIELD1 INTEGER);

--DELETING THE WHOLE TABLE
DROP TABLE EMPLOYEE;

--DELETING THE DATA IN THE TABLE BUT REMAINS THE TABLE
DELETE ALL EMPLOYEE;

--CREATE A TABLE THAT DOES NOT ALLOW DUPLICATES
CREATE SET TABLE TABLE1;

--CREATE A TABLE THAT ALLOWS DUPLICATES
CREATE MULTISET TABLE TABLE1;

--CREATE A TABLE WITH RESTRICTIONS
CREATE MULTISET TABLE TABLE_1
,FALLBACK, NO JOURNAL
,FREESPACE=10 PERCENT
,DATABLOCKSIZE = 16384 BYTES
(FIELD1 INTEGER);

--CREATE AND PRACTICE WITH DATA PROPERTIES
CREATE TABLE EMP_DATA
(EMPLOYEE_NUMBER INTEGER NOT NULL
,DEPARTMENT_NUMBER SMALLINT NOT NULL WITH DEFAULT
,JOB_CODE INTEGER TITLE 'ADDRESS'
,LAST_NAME CHAR(20) DEFAULT 'BOISE'
,FIRST_NAME VARCHAR(20) WITH DEFAULT
,BIRTHDATE DATE FORMAT 'MM/DD/YYYY'
,SALARY_AMOUNT DECIMAL(10,2)
,SEX CHAR(1) UPPERCASE)

--CREATE A TABLE WITH VARIOUS CONSTRAINTS
CREATE TABLE EMPLOYEE_BADGE
(EMP_ID INTEGER NOT NULL
,ID_BADGE_NUM INTEGER NOT NULL
,SALARY INTEGER
,JOB_CODE INTEGER
,CONSTRAINT PRIMARY_1 PRIMARY KEY(EMP_ID)
,CONSTRAINT UNIQUE_1 UNIQUE(ID_BADGE_NUM)
,CONSTRAINT CHECK_1 CHECK(SALARY>0 AND JOB_CODE BETWEEN 100000 AND 499999)
,CONSTRAINT REF_1 FOREIGN KEY (JOB_CODE)
REFERENCES JOB(JOB_CODE));


