SELECT PROD_NAME
FROM PRODUCTS
WHERE NOT VEND_ID='DLL01'
ORDER BY PROD_NAME;

--CONVERGING FUNCTIONS
SELECT
	COUNT(SALARY_AMOUNT) (TITLE 'COUNT')
	,SUM(SALARY_AMOUNT) (TITLE 'SUM//SALARY')
	,AVG(SALARY_AMOUNT) (TITLE 'AVG//SALARY')
	,MAX(SALARY_AMOUNT) (TITLE 'MAX//SALARY')
	,MIN(SALARY_AMOUNT) (TITLE 'MIN//SALARY')
FROM EMPLOYEE;

-- COUNT THE SUM OF SALARY OF EACH DEPARTMENT
SELECT DEPARTMENT_NUMBER
	,SUM(SALARY_AMOUNT)
FROM EMPLOYEE
GROUP BY DEPARTMENT_NUMBER;

--COUNT THE SUM OF SALARY OF 401 AND 403 DEPARTMENT
SELECT DEPARTEMENT_NUMBER
		,SUM(SALARY_AMOUNT)
FROM EMPLOYEE
WHERE DEPARTMENT_NUMBER IN (401,403)
GROUP BY DEPARTMENT_NUMBER;

SELECT DEPARTMENT_NUMBER AS DEPT
	,COUNT(*) AS #_EMPS
	,CAST (SUM(SALARY_AMOUNT) AS FORMAT 'ZZ,ZZZ,ZZZ,ZZ9.99')
							   AS TOTAL
	,CAST (MAX(SALARY_AMOUNT) AS FORMAT 'ZZ,ZZZ,ZZZ,ZZ9.99')
							   AS HIGHEST
	,CAST (MIN(SALARY_AMOUNT) AS FORMAT 'ZZ,ZZZ,ZZZ,ZZ9.99')
							   AS LOWEST
	,CAST (AVG(SALARY_AMOUNT) AS FORMAT 'ZZ,ZZZ,ZZZ,ZZ9.99')
							   AS_AVERAGE
FROM EMPLOYEE
GROUP BY DEPARTMENT_NUMBER
ORDER BY DEPARTMENT_NUMBER;

--CALCULATE THE AMOUNT OF THE TOTAL SALARY OF THE PARTICAULAR DEPARTMENT 
SELECT DEPARTMENT_NUMBER
		,JOB_CODE
		,SUM(SALARY_AMOUNT)
FROM EMPLOYEE
WHERE DEPARTMENT_NUMBER IN (401,403)
GROUP BY DEPARTMENT_NUMBER,JOB_CODE
ORDER BY 1,2;

--USING THE FUNCTION TO CALCULATE THE SALARY
SELECT  DEPARMTNET_NUMBER
		,COUNT(*)
		,SUM(SALARY_AMOUNT)
		,MAX(SALARY_AMOUNT)
		,MIN(SALARY_AMOUNT)
		,AVG(SALARY_AMOUNT)
FROM EMPLOYEE
GROUP BY DEPARTMENT_NUMBER
HAVING AVG(SALARY_AMOUNT)<36000;

--USE OF COUNT
SELECT EMPLOYEE_NUMBER
		,DEPARTMENT_NUMBER
		,MANAGER_EMPLOYEE_NUMBER(NAMED MANAGER)
FROM EMPLOYEE
WHERE EMPLOYEE_NUMBER BETWEEN 1003 AND 1008
WITH COUNT (MANAGER)(TITLE 'TOTAL MANAGERS');

--USE OF UNION
SELECT FIRST_NAME
		,LAST_NAME
		,'EMPLOYEE'(TITLE 'EMPLOYEE/TYPE')
FROM EMPLOYEE
WHERE MANAGER_EMPLOYEE_NUMBER = 1019
UNION 
SELECT SELECT FIRST_NAME
		,LAST_NAME
		,'MANAGER'
FROM EMPLOYEE
WHERE EMPLOYEE_NUMBER=1019
ORDER BY 2; 

--THE USAGE OF NOT 
SELECT PROD_NAME FROM PRODUCTS
WHERE NOT VEND_ID='DLL01'
ORDER BY PROD_NAME;

SELECT VEND_ID, COUNT(*) AS NUM_PRODS
FROM PRODUCTS
GROUP BY VEND_ID;

--HOW TO INSERT INTO THE LIST, TRY TO MAINTAIN THE 'INTO' TO MAKE SURE THE CODE IS AVAILABLE ON MANY SQLS
INSERT INTO CUSTOMERS(
		CUST_ID
		,CUST_NAME
		,CUST_ADDRESS)
VALUES('1000006'
		,'TOY LAND'
		,'123 STREET');
		
--CREATE A VIEW OF THE LIST
CREATE VIEW EMP_403
AS SELECT EMPLOYEE_NUMBER
		   ,LAST_NAME
		   ,SALARY_AMOUNT
		   FROM EMPLOYEE
		   WHERE DEPARTMENT_NUMBER=403;
SELECT *
FROM EMP_403;




		