DATABASE	CUSTOMER_SERVICE;
GRANT	SELECT 
	ON	CUSTOMER_SERVICE TO DBC;

--USING NICKNAMES ON LISTS
SELECT E.EMPLOYEE_NUMBER,
E.LAST_NAME,
D.DEPARTMENT_NAME
FROM EMPLOYEE E,
DEPARTMENT D
WHERE E.DEPARTMENT_NUMBER=D.DEPARTMENT_NUMBER;

--USING NICKNAMES IN INNER JOINING 
SELECT E.EMPLOYEE_NUMBER,
E.LAST_NAME,
D.DEPARTMENT_NAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPARTMENT_NUMBER=D.DEPARTMENT_NUMBER;

--CROSS JOINING PRACTICE
SELECT E.EMPLOYEE_NUMBER,
D.DEPARTMENT_NUMBER
FROM EMPLOYEE E
CROSS JOIN DEPARTMENT D
WHERE E.EMPLOYEE_NUMBER=1008;

--BAD EXAMPLE WHICH CREATED CROSS PRODUCT
SELECT EMPLOYEE.EMPLOYEE_NUMBER
,D.DEPARTMENT_NAME
FROM
EMPLOYEE E 
INNER JOIN DEPARTMENT D
ON E.DEPARTMENT_NUMBER = D.DEPARTMENT_NUMBER;

--BAD EXAMPLE WHICH CREATED CROSS PRODUCT BECAUSE OF WRONG CONDITION
SELECT E.EMPLOYEE_NUMBER,
D.DEPARTMENT_NAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON 3=3;

--BAD EXAMPLE WHICH CREATED CARTESIAN PRODUCT
SELECT E.EMPLOYEE_NUMBER,
D.DEPARTMENT_NUMBER
FROM EMPLOYEE E
CROSS JOIN DEPARTMENT D;

--AN EXAMPLE OF JOINING MULTI LISTS
SELECT E.LAST_NAME,
D.DEPARTMENT_NAME,
J.DESCRIPTION
FROM EMPLOYEE E INNER JOIN DEPARTMENT D
ON E.DEPARTMENT_NUMBER = D.DEPARTMENT_NUMBER
INNER JOIN JOB J
ON E.JOB_CODE = J.JOB_CODE;

--AN EXMAPLE OF SELF JOINING
SELECT EMP.FIRST_NAME(TITLE 'EMP//FIRST NAME')
,EMP.LAST_NAME (TITLE 'EMP//LAST NAME')
,MGR.FIRST_NAME(TITLE 'MGR//FIRST NAME')
,MGR.LAST_NAME (TITLE 'MGR//LAST NAME')
FROM EMPLOYEE EMP,
EMPLOYEE MGR
WHERE EMP.MANAGER_EMPLOYEE_NUMBER=MGR.EMPLOYEE_NUMBER 
AND EMP.LAST_NAME = 'BROWN';

--THE ALTERNATIVE WAY OF THE EXAMPLE ABOVE
SELECT EMP.FIRST_NAME(TITLE 'EMP//FIRST NAME')
,EMP.LAST_NAME (TITLE 'EMP//LAST NAME')
,MGR.FIRST_NAME(TITLE 'MGR//FIRST NAME')
,MGR.LAST_NAME (TITLE 'MGR//LAST NAME')
FROM EMPLOYEE EMP
INNER JOIN EMPLOYEE MGR
ON EMP.MANAGER_EMPLOYEE_NUMBER=MGR.EMPLOYEE_NUMBER 
AND EMP.LAST_NAME = 'BROWN';

--JOINING LISTS NOT BY SUBQUERY(FIRST OF THE TWO WAYS) 
SELECT EMPLOYEE.FIRST_NAME
,EMPLOYEE.LAST_NAME
,EMPLOYEE.DEPARTMENT_NUMBER
FROM EMPLOYEE
INNER JOIN DEPARTMENT 
ON EMPLOYEE.DEPARTMENT_NUMBER = DEPARTMENT.DEPARTMENT_NUMBER
WHERE DEPARTMENT.DEPARTMENT_NAME LIKE '%RESEARCH%';

--JOINING LISTS BY SUBQUERY(SECOND OF THE TWO WAYS)
SELECT FIRST_NAME
,LAST_NAME
,DEPARTMENT_NUMBER
FROM EMPLOYEE
WHERE DEPARTMENT_NUMBER IN
(SELECT DEPARTMENT_NUMBER 
FROM DEPARTMENT 
WHERE DEPARTMENT_NAME LIKE '%RESEARCH%');
